### ISSUE TITLE
Azure AD Graph API being retired

### ISSUE THREAD

**Issue by jrnewton** [halliba/az-pipelines-2-sharepoint#10]
Is this extension affected by the upcoming retirement of Azure AD Graph API? 

Announcement:
https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-change-management-simplified/ba-p/2967456

**Comment by MHebes** [comment]
Microsoft recommends migrating to Microsoft Graph instead, which this extension is [already using](https://github.com/halliba/az-pipelines-2-sharepoint/blob/main/buildAndReleaseTask/src/uploader.ts#LL1C2-L1C2). So it should not be affected.

**Comment by halliba** [comment]
Hi,

the extension does not use the old Azure AD Graph API, so it is not affected.
