### ISSUE TITLE
Update sourceFolder attribute in Sample YAML config files in README

### ISSUE THREAD

**Issue by jasonrastovski** [halliba/az-pipelines-2-sharepoint#13]
Not a big issue, but caused me a little bit of troubleshooting time.

The attribute name should say "sourceFolder" and not "source".  I copied/pasted your example and couldn't figure out why it wasn't parsing the $(Build.ArtifactStagingDirectory) for my file(s).  

![image](https://github.com/halliba/az-pipelines-2-sharepoint/assets/1902730/c52dd828-0c1c-46c3-930f-8e547e5c5088)

**Comment by halliba** [comment]
Thank you, you're correct.
I've fixed it.
