### ISSUE TITLE
Timeout for longer pushes

### ISSUE THREAD

**Issue by donh7644** [halliba/az-pipelines-2-sharepoint#14]
If the files being pushed are numerous you can receive a time out during the process.

failed, reason: connect ETIMEDOUT

**Comment by halliba** [comment]
Hi,

how large are the files, that you try to upload?

**Comment by donh7644** [comment]
They are small.... just numerous. Probably nothing more than a few kilobytes. They are small SQL files.

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 1, 2023 at 6:27 PM, ***@***.***> wrote:   


Hi,

how large are the files, that you try to upload?

**Comment by donh7644** [comment]
Oddly enough, I tried it again with no issues. The timeout is set to 0, so who knows...maybe the connection dropped. I'll comment again if I see the problem again. Thanks so much!
