### ISSUE TITLE
[Help needed] ##[error]Input required: failOnEmptySource

### ISSUE THREAD

**Issue by karoleaton** [halliba/az-pipelines-2-sharepoint#4]
Having successfully set all the parameters I am now getting the following error? I have left the source parameter as empty since I create the text file in the root when I run my script.. Should I be specifying something else? Thank you for help in advance!
![image](https://user-images.githubusercontent.com/102539420/186135931-17c37635-0673-4b84-a931-93e29c758da9.png)
![image](https://user-images.githubusercontent.com/102539420/186135983-aa2f9f6d-a661-4d4e-a778-52da21df8bfe.png)

![image](https://user-images.githubusercontent.com/102539420/186136271-a339a35c-bd11-46f2-97a1-75ff7a1ed3d6.png)
![image](https://user-images.githubusercontent.com/102539420/186136298-945fffe2-492f-4250-ba76-4470ec0ba9a7.png)

![image](https://user-images.githubusercontent.com/102539420/186136341-e4d2854e-1ccd-4f1b-9eb2-c1f0b6947a9d.png)
![image](https://user-images.githubusercontent.com/102539420/186136398-dffe3fd4-a231-4ae3-acce-eec6be01bccb.png)

**Comment by domeniconicoli** [comment]
I'm getting the same error and the **failOnEmptySource** parameter is not available on the "Advanced" tab. 

![image](https://user-images.githubusercontent.com/44091193/186138650-bb55d21c-897a-408a-a1b7-22930f729df8.png)

![image](https://user-images.githubusercontent.com/44091193/186138364-c2421c12-3d98-4063-b58c-f3a84b1aca1d.png)

This is probably related to [this](https://github.com/halliba/az-pipelines-2-sharepoint/commit/32496cd93336e23dc55a26f98459635a48f7f905)

**Comment by halliba** [comment]
Hi,

looks like the Azure Pipelines UI is not using the latest version but the agent does?...
That might be a "bug" in Azure DevOps.
Anyway I will publish a new version with a workaround ASAP.

Can you please check the extension page of your DevOps organization / Server for the Extension version?
And please try to add a new task and check if the option is visible for the new task.

**Comment by domeniconicoli** [comment]
> Hi,
> 
> looks like the Azure Pipelines UI is not using the latest version but the agent does?... That might be a "bug" in Azure DevOps. Anyway I will publish a new version with a workaround ASAP.
> 
> Can you please check the extension page of your DevOps organization / Server for the Extension version? And please try to add a new task and check if the option is visible for the new task.

yes, the version is fine. I also tried to re-add the task but with no luck :(

![image](https://user-images.githubusercontent.com/44091193/186141873-f253dcb3-e7f0-47c0-9bcd-b7af247645cd.png)

I'm trying now with the 0.3.1

**Comment by karoleaton** [comment]
HI @halliba the version on the the DevOps org is the latest:
![image](https://user-images.githubusercontent.com/102539420/186141990-e5be44e2-a9ac-4b13-8e34-881c7f7b243f.png)

I also tried to re-add the task on a new pipeline with no luck!

**Comment by domeniconicoli** [comment]
it works now and I can also see the setting under Advanced!
![image](https://user-images.githubusercontent.com/44091193/186143124-861958f2-b4bf-4858-9b36-e0f371c02f01.png)

thank you @halliba

**Comment by halliba** [comment]
Acutally i found the problem - there was a difference between the task .json manifest files.. I may have to check my build scripts...

I've published another release v0.3.2. Now the parameter actually shows up and works as expected.
