### ISSUE TITLE
[Help needed] Error: ##[error]Could not find drive and ##[error]Invalid driveId

### ISSUE THREAD

**Issue by karoleaton** [halliba/az-pipelines-2-sharepoint#5]
I have been receiving the following error regardless in which format I place the SharePoint url in:
![image](https://user-images.githubusercontent.com/102539420/186171026-59727601-24e7-4005-8c6c-8806f39733b9.png)

Also is the path format for the target folder in the "Target Folder" parameter like so:
![image](https://user-images.githubusercontent.com/102539420/186172367-b58e93ba-e6c8-4597-ba5d-33ab148ed567.png)
If the folder I want to publish to is in the Documents (no subfolders) of the site I wish to publish to?

Sorry for raising so many issues - appreciate the help!

**Comment by halliba** [comment]
Hi,

If possible, can you try entering the following query in Microsoft Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer):
`https://graph.microsoft.com/v1.0/sites/<tenant>.sharepoint.com:/<sites or teams>/<site-name>`
e.g.:
`https://graph.microsoft.com/v1.0/sites/contoso.sharepoint.com:/sites/mysite`
(The `:` is not a typo.)

Do you get a result?

If so, copy the id of the site and check this query:
`https://graph.microsoft.com/v1.0/sites/<site-id>/drives`

Find the library you want to use and compare the `webUrl` with the url you used in the task.
And now that you found your driveId, you can try to use that one in the task to check if it's a general problem with the site/drive.

Thank you :)

**Comment by breakpoint7** [comment]
Running into this same issue.  Tried the URL, Drive ID (using the recommendations above), etc.  I even used a basic Shared Documents default which is the example.  Same error.

**Comment by halliba** [comment]
Hi @breakpoint7,
I already updated the code to show more information (and the correct error message from the drive api) on a drive-related failure. Will be included in the next release.
Thank you for updating your question!

**Comment by mdzgua** [comment]
Hi @halliba
i have the same errors as @karoleaton, maybe exist one more solution ? :)

tenant ID, client ID, secret, api permissions are right as in your manual...
I checked all querries in MS Graph from your comment [on Aug 24] and the webUrl is correct, when using driveid in the errors are same...

Please help!

**Comment by halliba** [comment]
Hi, I've added some new error handling in v0.3.3.
If you still have these issues, please try again.

**Comment by mdzgua** [comment]
Hi, thn you for updating, still error...
previous was like 
![Screenshot_59](https://user-images.githubusercontent.com/120173366/210211846-3de43143-822b-4675-823b-17dbe61e7cbc.jpg)

after your update
![Screenshot_60](https://user-images.githubusercontent.com/120173366/210211882-4ab96ed2-7c38-4da5-9cc2-ffe9c5fd2b90.jpg)

**Comment by mdzgua** [comment]
Its ok now, thank you! :)
