### ISSUE TITLE
[Question/Documentation] - TargetFolder Creation

### ISSUE THREAD

**Issue by pri-kise** [halliba/az-pipelines-2-sharepoint#6]
Does this azure devops task create a target folder in sharepoint or will this lead to an error?
We are currently still using an old depracted solution (https://marketplace.visualstudio.com/items?itemName=projectumapsvsts.upload-sp-files-app&targetId=e90a45e5-af43-4897-8059-b28e1d8ebea2) to upload our files to sharepoint and we receive some very strange error, when the Target Folder does not exist.

I checked the documentation, but I couldn't find any details if the target folder must exist.

**Comment by halliba** [comment]
Hi pri-kise,

the document library / drive itself has to exist.
But the target folder within the drive will be created automatically. Not even by the task, but by the Microsoft Graph API itself.
I've just tried to upload files into an empty drive with parameter `targetFolder: /1/2/3/` and it worked fine.

Can you tell me what error you get? Do you use full access permissions or per library permissions?

**Comment by pri-kise** [comment]
@halliba thanks for the clarifaction and the update of the README file.
I didn't receive any errors with your awesome extension, but wit the old deprecated solution (mentioned above).
I only wanted to be sure that we can easily transfer our current pipeline tasks to your devops task.
