### ISSUE TITLE
Found file, but then not found

### ISSUE THREAD

**Issue by oscarjaergren** [halliba/az-pipelines-2-sharepoint#7]
So I can't get it working, it finds the file but still fails. 

I've verified Secret, DriveId e.t.c is correct using the Graph Explorer, but for some reason it seems to change the path and add in the 
"D:\a\1\s" twice when it tries to upload it. 

Input: 
- task: halliba.az-pipelines-2-sharepoint.az-pipelines-2-sharepoint.az-pipelines-2-sharepoint@0
  displayName: 'Upload files to SharePoint'
  inputs:
    tenantId: 'X'
    clientId: 'Y'
    clientSecret: 'Z'
    driveId: 'D'
    targetFolder: '/Releases/Software%20Releases'
    failOnEmptySource: true
    flattenFolders: true
    contents: 'D:/a/1/s/0 - Solution Items/Installer/*.exe'

I know for Certain the file folder path is
D:\a\1\s\0 - Solution Items\Installer\X.V.2.7.4-Debug.exe

ErrorMessageBelow: 
==============================================================================
Task         : Upload files to SharePoint Online
Description  : Upload files to SharePoint Online
Version      : 0.3.2
Author       : halliba (github.com/halliba)
I know forHelp         : [github.com/halliba/az-pipelines-2-sharepoint](https://github.com/halliba/az-pipelines-2-sharepoint)
==============================================================================
Found 1 files in 'D:\a\1\s'.
Validating drive id / url: 'X'.
Found drive 'Documents'.
Copying files to /Releases/Software%20Releases'
[1/1] Copying 'D:/a/1/s/0 - Solution Items/Installer/X-Debug.exe' -> '\Releases\Software%20Releases\X.V.2.7.4-Debug.exe'
{ Error: ENOENT: no such file or directory, stat 'D:\a\1\s\D:\a\1\s\0 - Solution Items\Installer\X.V.2.7.4-Debug.exe'
    at Object.statSync (fs.js:855:3)
    at Uploader.<anonymous> (D:\a\_tasks\az-pipelines-2-sharepoint_1ed28650-ea93-45a3-8f29-d0400ad51ce9\0.3.2\dist\src\uploader.js:104:44)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_tasks\az-pipelines-2-sharepoint_1ed28650-ea93-45a3-8f29-d0400ad51ce9\0.3.2\dist\src\uploader.js:28:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -4058,
##[error]ENOENT: no such file or directory, stat 'D:\a\1\s\D:\a\1\s\0 - Solution Items\Installer\X.V.2.7.4-Debug.exe'
  syscall: 'stat',
  code: 'ENOENT',
  path:
   'D:\\a\\1\\s\\D:\\a\\1\\s\\0 - Solution Items\\Installer\\X-Debug.exe' }

**Comment by halliba** [comment]
Hi oscarjaergren,

I currently try to pin down the exact problem..
From this line: `[1/1] Copying 'D:/a/1/s/0 - Solution Items/Installer/X-Debug.exe' -> '\Releases\Software%20Releases\X.V.2.7.4-Debug.exe', we know that the relative path to the file is `D:/a/1/s/0 - Solution Items/Installer/X-Debug.exe` when it should be `0 - Solution Items/Installer/X-Debug.exe`.
Can you tell me the original task inputs for `sourceFolder` (I assume it's blank) and `contents` including any variables?

Thank you!
